#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  1 08:58:11 2022

@author: hypnos
"""

import numpy as np

fileObject = open("/home/nwk/Desktop/AoC/Day1/day1_input.txt", "r")
data = fileObject.read()

myarray = data.split("\n\n")

summed = []    

for line in myarray:
    splitted = line.split("\n")
    if not np.char.isnumeric(splitted[-1]):
        del splitted[-1]
    summed.append(np.sum([int(x) for x in splitted]))
    
maxed = np.amax(summed)
print(maxed)

top_three_sum = np.sum(np.sort(summed)[-3:])
print(top_three_sum)
